apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: prod-

labels:
  - pairs:
      environment: production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: django-web
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: nginx
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: django-qcluster
  - patch: |-
      - op: replace
        path: /data/DEBUG
        value: "False"
      - op: replace
        path: /data/ALLOWED_HOSTS
        value: "yourdomain.com,www.yourdomain.com"
    target:
      kind: ConfigMap
      name: django-config

# Use specific production image tag
images:
  - name: your-registry/django-base
    newName: django-base
    newTag: v1.2.0 # Use semantic versioning
