apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django-base

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - django-deployment.yaml
  - nginx-deployment.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      project: django-base
      managed-by: kustomize
