apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-base
type: Opaque
stringData:
  # IMPORTANT: Replace these values in production!
  # IMPORTANTE: Substitua estes valores em produção!
  SECRET_KEY: ")@jw2)@ih8tjc@&6f)12xmdpwc$l48jad)7b@ppcw%1d^pne97@\\)7$r_vs6fif#_4&0$@"
  POSTGRES_PASSWORD: "changeme"
  GRAFANA_ADMIN_PASSWORD: "admin"
  # Portfolio settings
  PORTFOLIO_NAME: "Miguel de Freitas Muniz"
  PORTFOLIO_EMAIL: "miguimuniz@gmail.com"
  PORTFOLIO_GITHUB: "mugubr"
  PORTFOLIO_LINKEDIN: "miguel-de-freitas-muniz"
  PORTFOLIO_BIO:
    "Software developer with over three years of experience driving complex,
    high-impact projects."
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: django-base
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme"
